- name: Deploy PostgreSQL Cluster with High Availability
  hosts: patroni
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Import PostgreSQL repository key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
    
    - name: Add PostgreSQL APT repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
        state: present


    - name: Install PostgreSQL packages
      apt:
        name:
          - postgresql-13
          - postgresql-client-13
        state: present
    
    