- name: Deploy etcd Cluster
  hosts: etcd
  become: true

  vars:
    version: 3.5.8
    etcd_directory: /opt/etcd
    bin_directory: "{{ etcd_directory }}/bin"
    data_directory: /etcd/data-dir
    wal_directory: /etcd/wal-dir
    etc_directory: /etc/etcd
    user: etcd
    
  tasks:
    - name: Create etcd Group
      ansible.builtin.group:
        name: '{{ user }}'

    - name: Create etcd User
      ansible.builtin.user: 
        name: '{{ user }}'
        group: '{{ user }}'

    - name: "Create directory for etcd binaries and data directories"
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0775
        recurse: yes
      with_items:
        - '{{ bin_directory }}'
        - '{{ data_directory }}'
        - '{{ wal_directory }}'



    - name: Download the tarball into the tmp directory
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/etcd/v{{ version }}/etcd-v{{ version }}-linux-amd64.tar.gz
        dest: /tmp/etcd.tar.gz
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0774
        force: True

    - name: "Extract the contents of the tarball"
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: '{{ bin_directory }}'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0774
        extra_opts:
          - --strip-components=1
        decrypt: True
        remote_src: True
    
    - name: "Set permissions for etcd"
      file:
        path: '{{ bin_directory }}/etcd'
        state: file
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0774

    - name: "Set permissions for etcdctl"
      file:
        path: '{{ bin_directory }}/etcdctl'
        state: file
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0774
    
    - name: Get etcd version
      shell: '{{ bin_directory }}/etcd --version'
      register: etcd_version
      become: yes
    
    - name: Print etcd version
      debug: 
        msg: "{{ etcd_version }}"
    
    - name: "Add /opt/etcd/bin/ to the $PATH environment variable"
      lineinfile:
        path: /etc/profile
        line: export PATH="$PATH:/opt/etcd/bin"
        state: present
        create: True
        insertafter: EOF
    
    - name: "Set the ETCDCTL_API environment variable to 3"
      lineinfile:
        path: /etc/profile
        line: export ETCDCTL_API=3
        state: present
        create: True
        insertafter: EOF
    
    - name: "Create directory for etcd configure"
      file:
        path: '{{ etc_directory }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0775

    - name: Create etcd config
      template: 
        src: etcd.yml.j2
        dest: "{{ etc_directory }}/etcd.yml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0775

    - name: Create etcd service
      template: 
        src: etcd.service.j2
        dest: "/etc/systemd/system/etcd.service"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0775
    
    - name: Start etcd service
      systemd:
        name: etcd
        state: restarted
      become: yes


    - name: Fetch service logs
      command:
        cmd: journalctl -u etcd.service --no-pager
      register: journal_output

    - name: Show journal output
      debug:
        var: journal_output.stdout_lines