- name: Deploy etcd Cluster
  hosts: etcd
  become: true

  vars:
    version: 3.5.8
    bin_directory: /opt/etcd/bin
    etc_directory: /etc/etcd
    user: etcd
    
  
  tasks:
    - name: Create etcd Group
      ansible.builtin.group:
        name: '{{ user }}'

    - name: Create etcd User
      ansible.builtin.user: 
        name: '{{ user }}'
        group: '{{ user }}'

    - name: "Create directory for etcd binaries"
      ansible.builtin.file:
        path: '{{ bin_directory }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0700

    - name: Download the tarball into the tmp directory
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/etcd/v{{ version }}/etcd-v{{ version }}-linux-amd64.tar.gz
        dest: /tmp/etcd.tar.gz
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0600
        force: True

    - name: "Extract the contents of the tarball"
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: '{{ bin_directory }}'
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0600
        extra_opts:
          - --strip-components=1
        decrypt: True
        remote_src: True
    
    - name: "Set permissions for etcd"
      file:
        path: '{{ bin_directory }}/etcd'
        state: file
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0700

    - name: "Set permissions for etcdctl"
      file:
        path: '{{ bin_directory }}/etcdctl'
        state: file
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0700
    
    - name: Get etcd version
      shell: '{{ bin_directory }}/etcd --version'
      register: etcd_version
      become: yes
    
    - name: Print etcd version
      debug: 
        msg: "{{ etcd_version }}"
    
    - name: "Add /opt/etcd/bin/ to the $PATH environment variable"
      lineinfile:
        path: /etc/profile
        line: export PATH="$PATH:/opt/etcd/bin"
        state: present
        create: True
        insertafter: EOF
    
    - name: "Set the ETCDCTL_API environment variable to 3"
      lineinfile:
        path: /etc/profile
        line: export ETCDCTL_API=3
        state: present
        create: True
        insertafter: EOF
    
    - name: "Create directory for etcd configure"
      file:
        path: '{{ etc_directory }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: 0700

    - name: Create etcd config
      template: 
        src: etcd.yml.j2
        dest: "{{ etc_directory }}/etcd.yml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'

    - name: Create etcd service
      template: 
        src: etcd.service.j2
        dest: "/etc/systemd/system/etcd.service"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
    
    - name: Запустить сервис httpd
      systemd:
        name: etcd
        state: restarted
      become: yes